services:
  app:
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  db-data:
